<?php
//CONSTANT
const API_KEY_LEN = 15;
const API_SECRET_LEN = 30;
const ACCESS_TOKEN_LEN = 20;
const UPLOAD_REF_LEN = 40;
const SCAN_REF_LEN = 60;
const PARALLEL_ACCESS_TOKEN_LIMIT = 100;
const LIMITED_PARALLEL_ACCESS_CHECK_ENABLED = false;
const PARALLEL_SCANS_LIMIT = 1000;
const REQUEST_ID_LEN = 20;
const DEFAULT_TTL_VALUE = 86400;

//SUCCESS CODES
const SUCCESS 			= 200;
const ACCESS_TOKEN_EXTENDED = 201;
const ACCESS_TOKEN_FLUSHED  = 202;
const UPLOAD_SUCCESS = 203;
const SCAN_STARTED = 204;
const DIGEST_SUCCESS = 205;

//ERROR CODES
const KEY_REQUIRED 			= 101;
const ACCESSTOKEN_NOT_GENERATE	= 102;
const INVALID_SECRET 		= 103;
const VALIDATION_ERROR 	 		= 104;
const INVALID_SECRET_LEN 	= 105;
const SPECIALCHAR_IN_KEY 	= 106;
const LIMIT_CROSS 			= 107;
const INVALID_TOKEN_LEN 	= 108;
const SPECIALCHAR_IN_TOKEN 	= 109;
const TOKEN_EXPIRED 		= 110;
const INVALID_TOKEN 		= 111;
const INVALID_UPLOAD_ID_TYPE = 112;
const INVALID_UPLOAD_ID 	= 113;
const INVALID_UPLOAD_FILE 	= 114;
const UPLOAD_ERROR 			= 115;
const INVALID_SCAN_ID_TYPE 	= 116;
const INVALID_SCAN_ID 		= 117;
const UN_AUTH_LAUNCH 		= 118;
const SYSTEM_DB_ERROR       = 119;
const UPLOAD_LIST_EMPTY     = 120;
const UPLOAD_ID_IN_PROCESS  = 121;
const INVALID_API_SECRET  = 122;
const INVALID_API_LEN  = 123;
const UN_AUTH_UPLOADID  = 124;
const UN_AUTH_SCANID  = 125;
const INTERNAL_ERROR_GEN_ACCESSTOKEN  = 126;
const INTERNAL_ERROR_RENEW  = 127;
const FLUSHED  = 128;
const INTERNAL_ERROR_FLUSH  = 129;
const INTERNAL_ERROR_FILE_UPLOAD = 130;
const INTERNAL_ERROR_REG_UPLOADID = 131;
const UPLOAD_EMPTY = 132;
const INTERNAL_ERROR_SCAN_QUEUE = 133;
const SCAN_EMPTY = 134;
const KEY_SECRET_EMPTY = 135;
const TOKEN_EMPTY = 136;
const TOKEN_FILE_EMPTY = 137;
const UPLOAD_ID_EMPTY = 138;
const TOKEN_SCANID_EMPTY = 139;
const USER_SUSPENDED = 140;
const SCAN_LIMIT_CROSSED = 141;

const SPECIALCHAR_IN_UPLOAD_REF = 142;
const INVALID_UPLOAD_REF_LEN = 143;
const SPECIALCHAR_IN_SCAN_REF = 144;
const INVALID_SCAN_REF_LEN = 145;
const APP_DIGEST_NOT_EXIST = 146;

const FIELD_MISSING = 147;
const EMAIL_REQUIRED = 148;
const NAME_REQUIRED = 149;
const CONTACT_REQUIRED = 150;
const EMAIL_NOT_VALID = 151;
const EMAIL_NOT_INSERT_LOGIN_TABLE = 152;

const USER_INSERT_ERROR = 153;
const USER_PREFERENCE_INSERT_ERROR = 154;
const USER_PLAN_INSERT_ERROR = 155;
const EMAIL_ALREADY_EXIST = 156;
const EMAIL_NOT_EXIST = 157;
const NAME_NOT_UPDATE = 158;

const USER_PLAN_EXPIRED = 159;
const UPLOAD_LIMIT_CROSSED = 160;
const USER_ID_NULL = 161;
const SERVER_SCAN_LIMIT_CROSSED = 162;

const ACCESSTOKEN_REQUIRED = 163;
const USERNAME_REQUIRED = 164;
const PASSWORD_REQUIRED = 165;
const SPECIALCHAR_IN_CREDENTIALS = 166;
const NUMBER_IN_USERNAME = 167;
const CREDENTIALS_TOO_LONG = 168;
const INTERNAL_ERROR_INSERT_CREDENTIAL = 169;
const SPECIALCHAR_IN_CREDENTIAL_REF = 170;
const CREDENTIAL_REF_LENGTH_INVALID = 171;
const CREDENTIAL_REF_NOT_EXIST = 172;
const INTERNAL_ERROR_UPDATE_CREDENTIAL = 173;
const UPDATE_FIELD_REQUIRED = 174;
const CREDENTIAL_REF_REQUIRED = 175;
const INTERNAL_ERROR_DELETE_CREDENTIAL = 176;
const CREDENTIAL_USER_ALREADY_EXIST = 177;
const GIVEN_CREDENTIALS_NOT_VALID = 178;
const APK_FILE_SIZE_EXCEEDED = 179;
const UNAUTHORIZED_TO_GENERATE_ACCESS_TOKEN = 180;
const PLAN_SCAN_LIMIT_CROSSED = 181;

const ECLIPSE_LICENSE_REQUIRED = 182;
const ECLIPSE_PRODUCT_ID_REQUIRED = 183;
const API_SECRET_REQUIRED = 184;
const API_KEY_REQUIRED = 185;
const INVALID_ECLIPSE_PRODUCT = 186;
const INVALID_ECLIPSE_LICENSE = 187;
const ECLIPSE_LICENSE_LENGTH_MISMACH = 188;
const NOT_UPDATE_LAST_VALIDATED_ON = 189;
const USER_AGENT_NOT_RECOGNIZE = 190;
const INSUFFICIENT_PARAMETER = 191;
const INCORRECT_PARAMETER = 192;
const REQUEST_LIMIT_CROSSED = 193;

const UNAUTHORIZED_ACCESS = 194;
const INVALID_DEVICE_ID = 195;
const NAME_NOT_VALID = 196;

const TTL_NOT_VALID = 197;
const APP_DIGEST_NOT_VALID = 198;
const INVALID_APP = 199;
const CREDENTIAL_LIST_EMPTY = 1101;

const INVALID_SCAN_STATUS = 401;
const SCAN_ALREADY_STOPPED = 402;
const CORRUPTED_APP= 403;
?>
